---
title: "Final Project"
output: 
  html_document: 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Project -- Maturity Assessment

The purpose of this project is to take the lecture materials from the course and apply them in practice. To do this, I would like you to use the "four scenarios" from Chapter 2 to assess the BI maturity of some organization, apply your criteria to an organization you are involved with, and then describe how the organization can move from one level to another.

Imagine you are giving this report to your supervisor and it will serve as a blueprint for the work you will do over the next six months to a year. The primary objective is to increase the BI maturity of your organization and to improve the way you use data to make decisions.

Because you are delivering this to your supervisor, you should avoid using negative language or value judgements. If done correctly, it should be clear that the next step in the BI maturity model is much better than the current state of company operations. There is no need to state that operations could be improved or that current operations are not ideal. Negative language and value judgements generally make people defensive, not good if you're trying to persuade.

### A few notes about the organization you choose.

* The ideal situation is that you analyze your current employer. 
* You do not have to tell me the name of your employer, in fact, I prefer you don't. Simply choose a name to call the company throughout the report.
* You should not need to share any confidential details from your employer to successfully complete this assignment.
* If you are not currently employed or otherwise need to find another organization to analyze, please let me know before the end of the third week of this course.

### Required format

* The Four Scenarios from Chapter 2 will be used as a BI Maturity model.
* Copy the grid from 02.03 Four Scenarios slide 25 into your presentation.
* Highlight one item from each column representing the current state of the chosen organization.
* Create a section describing the current state of your organization. This section should have four sub-sections, one for each of the criteria (rows) in the model.
* Create a section describing how to move from the current level (columns) to the next level in the model. You should have four sub-sections, one for each criteria (row) in the model.
* Be as detailed as possible in your writing.
* Refer to the rubric for additional requirements.

### Notes
* Your paper does not have to be too long. You should be able to accomplish this in 3-5 pages.
* You do not need to make any value judgments about how well the organization is managed.
* Reminder that no confidential details are to be included in the paper.
* This is intended to be a write up in either a PDF or MS Word file. It is possible to create a Power Point presentation but I am likely to be more picky for projects submitted in that format.
